
# html lang
language: en

# Blog name
headername: Foxerlee's Journal

# main menu navigation
menu:
  Home: /
  Archive: /archives
  Categories: /
  Tags: /tag
  Friends: /friends
  About: /about
  Contact: /contact

# Author
author: Foxerlee

# Profile
profile_title: Foxerlee's Journal

# Links
## Comment if you don't use this link
## The display order is the order in _config.yml, you can change it to you want.
links:
  # douban: /#
  # bilibili: /#
  github: https://github.com/FoxerLee
  linkedin: https://www.linkedin.com/in/yuan-li-008b3b142/
  zhihu: https://www.zhihu.com/people/foxerlee/activities
  facebook: /#
  twitter: /#
  weibo: /#
  reddit: /#
  stack-overflow: /#
  gitlab: /#
  pinterest: /#
  youtube: /#

# Website start year
start_year: 2017

# Friends
##
friends:
  friend-1:
    name: Test
    url: http://www.zjzsliyang.com/
    image: /images/a6.jpg
  friend-2:
    name: Test
    url: http://www.zjzsliyang.com/
    image: /images/a6.jpg
  friend-3:
    name: Test
    url: http://www.zjzsliyang.com/
    image: /images/a6.jpg

friends_length: 3

# stylesheets loaded in the <head>
stylesheets:
- /css/style.css

# scripts loaded in the end of the body
scripts:
- /js/hexo-theme-terran.js
