
# html lang
language: en

# Blog name
headername: Foxerlee's Journal

# main menu navigation
menu:
  Home: /
  Blog: /archives
  Categories: /
  Tags: /
  Friends: /
  About: /about
  Contact: /contact

# Author
author: Foxerlee

# Profile
profile_title: Foxerlee's Journal

# Website start year
start_year: 2017

# stylesheets loaded in the <head>
stylesheets:
- /css/style.css

# scripts loaded in the end of the body
scripts:
- /js/hexo-theme-terran.js
