
# html lang
language: en

# Blog name
headername: Foxerlee's Journal

# main menu navigation
menu:
  Home: /
  Archive: /archives
  Categories: /category
  Tags: /tag
  Friends: /friends
  About: /about

favicon: /images/logo.jpeg


# Profile
profile_title: Foxerlee's Journal

# Links
## Comment if you don't use this link
## The display order is the order in _config.yml, you can change it to you want.
links:
  # douban: /#
  # bilibili: /#
  github: https://github.com/FoxerLee
  linkedin: https://www.linkedin.com/in/yuan-li-008b3b142/
  zhihu: https://www.zhihu.com/people/foxerlee/activities
  facebook: /#
  twitter: /#
  # weibo: /#
  # reddit: /#
  # stack-overflow: /#
  # gitlab: /#
  # pinterest: /#
  # youtube: /#

# Website start year
start_year: 2017

# Friends
##
friends:
  1:
    name: Test
    url: http://www.zjzsliyang.com/
    image: /images/a1.jpg
  2:
    name: Test
    url: http://www.zjzsliyang.com/
    image: /images/a2.jpg
  3:
    name: Test
    url: http://www.zjzsliyang.com/
    image: /images/a3.jpg
  4:
    name: Test
    url: http://www.zjzsliyang.com/
    image: /images/a4.jpg
friends_length: 4

date:
  month: MMM, YYYY
  day: MMM DD, YYYY

copyright: true
permalink: true
license: Copyright (c) <a href="http://creativecommons.org/licenses/by-nc/4.0/">CC-BY-NC-4.0</a> LICENSE
signature: stay hungry, stay foolish

visit_counter:
  site_uv: true
  site_pv: true


# Post wordcount display settings
# Dependencies: https://github.com/willin/hexo-wordcount
post_wordcount:
  wordcount: true         # 单篇 字数统计
  min2read: true          # 单篇 阅读时长

# stylesheets loaded in the <head>
stylesheets:
- /css/style.css

# scripts loaded in the end of the body
scripts:
- /js/hexo-theme-terran.js
- /js/md5.js
- /js/lazyLoad.js

gitalk:
  enable: true
  ClientID: # Client ID
  ClientSecret:  # Client Secret
  repo:  # repo which stores your blog
  owner: FoxerLee # Github account name
  adminUser: ['FoxerLee']
  ID: location.pathname
  labels: ['Gitalk'] # GitHub issues' tag
  perPage: 10 # How many comments in per page
  pagerDirection: last # first - old to new; last - new to old
  createIssueManually: false # if need admin user to create issue
  distractionFreeMode: false # if cmd|ctrl + enter can submit comment

about:
  avatar: /images/avatar.jpeg
  name: Foxerlee
  signature: 致我們短暫相遇，又各奔他處的一生
  education:
    1: Master of Computer Science, New York University
    2: Bachelor of Software Engineering, Tongji University
  experience:
    1: Software Develop Intern, Amazon
    2: Graduate Assistant, New York University
    3: Research Intern, National Instruments
    4: Software Intern, Microsoft
  interest: Machine Learning, Computer Vision, OCR, Segmentation, Few-shot Learning, Cybersecurity, Coding, Reading, Dota2, Fitness
  github_chart: Foxerlee

lazyload:
  enable: true
  onlypost: false
  loadingImage: https://cdn.jsdelivr.net/npm/skx@0.0.9/img/lazy.gif

googleads: ca-pub-3129494579607503